import { ProjectsObjProps } from '../../interfaces';
import { StyledBiLogoMongodb, StyledBiLogoRedux, StyledBiLogoTypescript, StyledDiReact, StyledDiSass, StyledFaNode, StyledGrMysql, StyledRiJavascriptFill, StyledSiStyledcomponents } from './styled';

export const projectsObj: ProjectsObjProps[] = [
    {
        name: 'Meu Portfolio',
        descricao: 'Meu projeto principal, colocando todo conhecimento em pratica',
        categories: ['front', 'build'],
        tecnologias: ['ReactTs ', 'Styled Components'],
        icons: [StyledDiReact, StyledBiLogoTypescript, StyledSiStyledcomponents],
        githubURL: 'https://github.com/edsuuu/edsuuu',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/portfolio.png',
        deploy: false,
        deployURL: '',
    },
    {
        name: 'Hydra Landing Page',
        descricao: 'Uma landing page com um visual moderno',
        categories: ['front', 'build'],
        tecnologias: ['ReactTs ', 'Styled Components'],
        icons: [StyledDiReact, StyledBiLogoTypescript, StyledSiStyledcomponents],
        githubURL: 'https://github.com/edsuuu/hydra-landing-page',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/hydra-landing-page/main/hydra-page.png',
        deploy: true,
        deployURL: 'https://hydra-landing-page-nu.vercel.app',
    },
    {
        name: 'NFT Landing Page',
        descricao: 'Uma landing page voltada para NFTs.',
        categories: ['front'],
        tecnologias: ['ReactJs ', 'Scss'],
        icons: [StyledDiReact, StyledRiJavascriptFill, StyledDiSass],
        githubURL: 'https://github.com/edsuuu/landing-page-nft',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/landing-page-nft/main/public/Home.PNG',
        deploy: true,
        deployURL: 'https://landing-page-nft-three.vercel.app',
    },

    {
        name: 'Front Escola',
        descricao: 'Front para consumir a Api_Escola',
        categories: ['front', 'fullstack'],
        tecnologias: ['ReactJs ', 'Javascript ', 'Styled Components ', 'Redux'],
        icons: [StyledDiReact, StyledRiJavascriptFill, StyledSiStyledcomponents, StyledBiLogoRedux],
        githubURL: 'https://github.com/edsuuu/front-escola ',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/front-escola/main/public/image.png',
        deploy: false,
        deployURL: '',
    },
    {
        name: 'Front Valorant',
        descricao: 'Front para consumir a Api_Valorant',
        categories: ['build', 'front', 'fullstack'],
        tecnologias: ['ReactTs ', 'TypeScript ', 'Styled Components ', 'Redux'],
        icons: [StyledDiReact, StyledBiLogoTypescript, StyledSiStyledcomponents, StyledBiLogoRedux],
        githubURL: 'https://github.com/edsuuu/AccontsValorant',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/valorant.png',
        deploy: false,
        deployURL: '',
    },
    {
        name: 'Api Valorant',
        descricao: 'Api para cadastro de contas com sistema admin e sistema de logs',
        categories: ['build', 'backend'],
        tecnologias: ['TypeScript ', 'Node ', 'MongoDB'],
        icons: [StyledBiLogoTypescript, StyledFaNode, StyledBiLogoMongodb],
        githubURL: 'https://github.com/edsuuu/api_contas_valorant',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/api-2.webp',
        deploy: false,
        deployURL: '',
    },
    {
        name: 'Api Escola',
        descricao: 'Api para cadastro de perfil de alunos com upload de fotos',
        categories: ['fullstack', 'backend'],
        tecnologias: ['Node ', 'MySql ', 'Sucrase'],
        icons: [StyledFaNode, StyledGrMysql],
        githubURL: 'https://github.com/edsuuu/api_escola',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/api-1.webp',
        deploy: false,
        deployURL: '',
    },
    {
        name: 'Agenda MVC ',
        descricao: 'Um projeto MVC, usanando EJS para desenvolvimento da interface, simula uma agenda de contatos',
        categories: ['fullstack', 'backend', 'front'],
        tecnologias: ['Node ', 'EJS ', 'MongoDB'],
        icons: [StyledFaNode, StyledBiLogoMongodb],
        githubURL: 'https://github.com/edsuuu/projeto_agenda_mvc',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/pj-agenda.png',
        deploy: false,
        deployURL: '',
    },
];
