import { ProjectsObjProps } from '../../interfaces';
import { StyledBiLogoMongodb, StyledBiLogoTypescript, StyledDiReact, StyledDiSass, StyledFaNode, StyledGrMysql, StyledRiJavascriptFill, StyledSiStyledcomponents } from './styled';

export const projectsObj: ProjectsObjProps[] = [
    {
        name: 'MicroSaas',
        descricao: 'MicroSaas para comercio sendo desenvolvido com Typescript, typeorm sequelize, e postgre',
        categories: ['fullstack', 'backend'],
        icons: [StyledFaNode, StyledGrMysql],
        githubURL: 'https://github.com/edsuuu/api_escola',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/api-3.webp',
        deploy: false,
        deployURL: '',
    },
    {
        name: 'Hydra Landing Page',
        descricao: 'Uma landing page com um visual moderno',
        categories: ['front', 'build'],
        tecnologias: ['ReactTs ', 'Styled Components'],
        icons: [StyledDiReact, StyledBiLogoTypescript, StyledSiStyledcomponents],
        githubURL: 'https://github.com/edsuuu/api-saas',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/hydra-landing-page/main/hydra-page.png',
        deploy: true,
        deployURL: 'https://hydra-landing-page-nu.vercel.app',
    },
    {
        name: 'NFT Landing Page',
        descricao: 'Uma landing page voltada para NFTs.',
        categories: ['front'],
        tecnologias: ['ReactJs ', 'Scss'],
        icons: [StyledDiReact, StyledRiJavascriptFill, StyledDiSass],
        githubURL: 'https://github.com/edsuuu/landing-page-nft',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/landing-page-nft/main/public/Home.PNG',
        deploy: true,
        deployURL: 'https://landing-page-nft-three.vercel.app',
    },
    {
        name: 'API Contas',
        descricao: 'Api para cadastro de contas de jogos, com autenticação e rotas protegidas',
        categories: ['build', 'backend'],
        tecnologias: ['TypeScript ', 'Node ', 'MongoDB'],
        icons: [StyledBiLogoTypescript, StyledFaNode, StyledBiLogoMongodb],
        githubURL: 'https://github.com/edsuuu/api_contas_valorant',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/api-2.webp',
        deploy: false,
        deployURL: '',
    },
    {
        name: 'Api Gestão de alunos',
        descricao: 'Api para cadastro de perfil de alunos com upload de fotos',
        categories: ['fullstack', 'backend'],
        tecnologias: ['Node ', 'MySql ', 'Sucrase'],
        icons: [StyledFaNode, StyledGrMysql],
        githubURL: 'https://github.com/edsuuu/api_escola',
        imageURL: 'https://raw.githubusercontent.com/edsuuu/edsuuu/main/public/Assets/api-1.webp',
        deploy: false,
        deployURL: '',
    },

];
